FRENCH_PUBLISHERS = [
            "Recherche Data Gouv",
            "Université de Lorraine",
            "NAKALA",
            "CIRAD",
            "INRAE",
            "INRA",
            "Ifremer",
            "DataSuds",
            "Strasbourg",
            "Paris",
            "CNES",
            "CIRAD",
            "Irstea",
            "ONERA",
            "France",
            "français",
            "française",
            "progedo",
            "Cergy-Pontoise",
            "UMS PatriNat",
            "UMR",
            "CNRS",
            "sciences po",
            "sciencespo",
            "occitanie",
            "doranum",
            "auvergne",
            "reims",
            "bordeaux",
            "nantes",
            "marseille",
            "lyon",
            "brest",
            "toulouse",
            "caen",
            "MNHN",
            "École des Hautes Études en Sciences Sociales",
            "Data Terra",
            "Supaéro",
            "Hautes Études en Sciences Sociales",
            "Institut Laue-Langevin",
            "Biologique de Roscoff",
            "histoire du temps présent",
            "IHU Méditerranée",
            "Gustave Eiffel",
            "cereq",
            "hal ccsd",
            "Nouvelle-Calédonie"
        ]
FRENCH_ALPHA2 = ["fr", "gp", "gf", "mq", "re", "yt", "pm", "mf", "bl", "wf", "tf", "nc", "pf"]
